// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXiWMtOSliEFZG22Bjyf9O1la8LH9u26I',
    appId: '1:316667010224:web:f47bf0d5e24aa5fe5e2f75',
    messagingSenderId: '316667010224',
    projectId: 'nf1005-firebase',
    authDomain: 'nf1005-firebase.firebaseapp.com',
    storageBucket: 'nf1005-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZTH298wHf5GfROMBePl1A-AxUM-9PX2k',
    appId: '1:316667010224:android:cfd032f370c065455e2f75',
    messagingSenderId: '316667010224',
    projectId: 'nf1005-firebase',
    storageBucket: 'nf1005-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaRirUJo26fwfxPa6u7n2Fqu08jKI28Zs',
    appId: '1:316667010224:ios:bcc22df67f3c9ed65e2f75',
    messagingSenderId: '316667010224',
    projectId: 'nf1005-firebase',
    storageBucket: 'nf1005-firebase.appspot.com',
    iosClientId: '316667010224-9uqohiealvj1ma37vc81l621bouruhc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nf1005Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaRirUJo26fwfxPa6u7n2Fqu08jKI28Zs',
    appId: '1:316667010224:ios:bcc22df67f3c9ed65e2f75',
    messagingSenderId: '316667010224',
    projectId: 'nf1005-firebase',
    storageBucket: 'nf1005-firebase.appspot.com',
    iosClientId: '316667010224-9uqohiealvj1ma37vc81l621bouruhc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nf1005Firebase',
  );
}
